######################################################################
# Automatically generated by qmake (3.0) Thu Oct 29 14:02:17 2015
######################################################################

QT+=widgets
TEMPLATE = app
TARGET = a3
INCLUDEPATH += .

# Input
HEADERS += objModel.h renderer.h window.h
SOURCES += main.cpp objModel.cpp renderer.cpp window.cpp
